num_epochs: 50
lr: 0.001
batch_size: 128
random_seed: 42
device: "cuda" # or "cpu"
dataset: "cifar10"
num_workers: 4
pin_memory: false
model_dir: "src/results"
model_path: "logits"
log_dir: "logs/cnn/logits"
experiment_name: "logits/train"
kd_weights: 0.1
teacher_model_dir: "src/results/teacher.pth"