num_epochs: 50
lr: 0.001
batch_size: 128
random_seed: 42
device: "cuda" # or "cpu"
dataset: "cifar10"
num_workers: 4
pin_memory: false
model_dir: "src/results"
model_path: "soft_target"
log_dir: "logs/cnn/soft_target"
experiment_name: "soft_target/train"
kd_weights: 1.
temperature: 4.
teacher_model_dir: "src/results/teacher.pth"