num_epochs: 200
lr: 0.001
batch_size: 64
random_seed: 42
in_channels: [64, 64, 64, 64]
layers: [3, 6, 4, 3]
device: "cuda" # or "cpu"
dataset: "cifar10"
num_workers: 4
pin_memory: true
model_dir: "src/results"
model_path: "teacher_resnet"
log_dir: "logs/resnet/teacher_resnet"
experiment_name: "teacher_resnet/train"
augmentation: true