num_epochs: 50
lr: 0.001
batch_size: 128
random_seed: 42
in_channels: [16, 32, 64, 128]
layers: [3,4,6,3]
device: "cuda" # or "cpu"
dataset: "cifar10"
num_workers: 4
pin_memory: false
model_dir: "src/results"
model_path: "teacher_resnet"
log_dir: "logs/resnet/teacher_resnet"
experiment_name: "teacher_resnet/train"