num_epochs: 50
lr: 0.001
batch_size: 128
random_seed: 42
device: "cuda" # or "cpu"
dataset: "cifar10"
num_workers: 4
pin_memory: false
model_dir: "src/results"
model_path: "logits_kd"
log_dir: "logs/logits_kd"
experiment_name: "logits_kd/train"
kd_weights: 0.1