num_epochs: 50
lr: 0.001
batch_size: 128
random_seed: 42
device: "cuda"  # or "cpu"
dataset: "cifar10"
num_workers: 4
pin_memory: false
model_dir: "src/results"
model_path: "student"
log_dir: "logs/student"
experiment_name: "student/train"